version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      production-patches:
        dependency-type: production
        update-types: [patch]
      development-patches:
        dependency-type: development
        update-types: [patch]
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
