/** A room scene: poster + optional native Rive layer + hotspots resolved to real destinations. Generated by scripts/stage-approved-assets.ts. */
export const ROOM = { width: 1648, height: 928 } as const;
export interface Hitbox { x: number; y: number; width: number; height: number }
export type HotspotTarget = { kind: 'page'; pageId: string; project?: string } | { kind: 'anchor'; anchor: string };
export interface SceneHotspot { id: string; label: string; hit: Hitbox; target: HotspotTarget; focusValue: string; trigger?: string }
export interface SceneRive { file: string; artboard: string; stateMachine: string; viewModel: string; sha256: string }
export interface SceneRecord { id: string; poster: string; posterAlt: string; rive: SceneRive | null; hotspots: SceneHotspot[]; captionRest: string; captions: Record<string, string> }
